export const missionCopy = {
  de: {
    nav: "An Bord", kicker: "MENSCHEN / WISSENSCHAFT / ORBIT", title: "Heute auf der ISS.", intro: "Die Menschen hinter dem Lichtpunkt. Die Forschung hinter der Mission.",
    open: "An Bord entdecken", crewTitle: "Wer ist an Bord?", crewIntro: "Die von NASA gemeldete Stationsbesatzung, ergänzt um Profile und Missionsdaten.", expedition: "Expedition", people: "Menschen an Bord", onboard: "An Bord laut NASA", reported: "ISS-Crew laut Community", commander: "Stationskommando", engineer: "Flugingenieur/in", crew: "Crewmitglied", arrived: "Ankunft", launched: "Start", days: "Tage seit Ankunft", profile: "Profil öffnen", source: "Quelle", credit: "Bildnachweis / Lizenz", fetched: "Abgerufen", fresh: "Quelle erreichbar", stale: "Letzter gespeicherter Stand", unavailable: "Quelle gerade nicht erreichbar", loading: "Stationsdaten werden geladen …", retry: "Neu laden", community: "NASA-Abgleich derzeit nicht verfügbar. Angezeigt wird die Community-Liste; Rollen werden nicht übernommen.", crewNote: "Crewwechsel erscheinen nach Aktualisierung der Quellen. Ein erfolgreicher Abruf ist keine sekundengenaue Bestätigung. Ankunft und Aufenthaltsdauer stammen aus der ergänzenden Missionsquelle.",
    researchTitle: "Forschung im Fokus.", researchIntro: "Was zuletzt aus dem Orbit berichtet wurde – verständlich erklärt und mit Originalquelle.", reportedAt: "Zuletzt berichtet", why: "Warum im All?", benefit: "Wofür ist das gut?", researchNote: "Die Karten zeigen zuletzt erwähnte Experimente, keinen Live-Stundenplan. Eine Erwähnung bestätigt nicht, dass ein Versuch gerade läuft.", newsTitle: "Neues von der Station", newsIntro: "Starts, Crewwechsel und Alltag direkt aus dem NASA-Stationsblog.", read: "Bei NASA weiterlesen ↗", original: "NASA-Originalberichte auf Englisch", allCrew: "Gesamte Crew & Forschung", noResearch: "Aktuell ist kein Forschungsbericht verfügbar.", noCrew: "Die Besatzung konnte nicht geladen werden.", noNews: "Der Nachrichtenfeed ist derzeit nicht erreichbar.",
    following: "◎ ISS verfolgen", freeView: "◎ Freie Ansicht", orbitPreview: "Nächste 90 Minuten · berechnet", orbitUnavailable: "Bahnvorhersage nicht verfügbar", orbitEpoch: "Bahndaten vom", solarNote: "Tag/Nacht nach Sonnenstand · Nachtlichter: NASA 2012 · Wolken illustrativ", dataTitle: "So bleiben die Inhalte aktuell", dataBody: "NASA-RSS liefert Stations- und Forschungsberichte. Die NASA-Expeditionsseite liefert Crew und Rollen; People in Space ergänzt Profile und Ankunftsdaten. Abfrage alle 10 Minuten bei sichtbarer Seite, mit Cache und getrennten Ausfallanzeigen. Bei Ausfällen werden gespeicherte Daten höchstens 24 Stunden gezeigt. Forschungsberichte behalten ihr Veröffentlichungsdatum.", orbitData: "Die 90-Minuten-Vorschau nutzt SGP4 und ISS-Bahnelemente (TLE). Elemente älter als sieben Tage werden abgelehnt. Die gemessene Position bleibt separat; die Höhe im Globus ist zur besseren Sichtbarkeit überhöht. Sonnenstand und Erdschatten nutzen ein astronomisches Näherungsmodell. Nachtlichter sind historische Aufnahmen, keine Livebilder.", brief: "Das Orbitlabor, jetzt.", briefIntro: "Besatzung, aktuelle Forschung und die neuesten Nachrichten aus rund 400 Kilometern Höhe.", measured: "Beleuchtung der ISS", trail: "Gemessene Spur", timeUnknown: "Datum nicht verfügbar"
  },
  en: {
    nav: "On board", kicker: "PEOPLE / SCIENCE / ORBIT", title: "Today on the ISS.", intro: "The people behind the point of light. The science behind the mission.",
    open: "Discover life on board", crewTitle: "Who is on board?", crewIntro: "The station crew listed by NASA, with profiles and mission details.", expedition: "Expedition", people: "people on board", onboard: "On board according to NASA", reported: "ISS crew reported by community", commander: "Station commander", engineer: "Flight engineer", crew: "Crew member", arrived: "Arrived", launched: "Launched", days: "days since arrival", profile: "Open profile", source: "Source", credit: "Image credit / license", fetched: "Retrieved", fresh: "Source available", stale: "Last saved update", unavailable: "Source currently unavailable", loading: "Loading station updates …", retry: "Refresh", community: "NASA cross-check unavailable. Showing the community roster without its role assignments.", crewNote: "Crew changes appear when sources update. A successful retrieval is not a real-time confirmation. Arrival dates and durations come from the supplementary mission source.",
    researchTitle: "Science in focus.", researchIntro: "Recently reported from orbit, with a plain-language explanation and the original source.", reportedAt: "Last reported", why: "Why in space?", benefit: "Why does it matter?", researchNote: "These cards show recently mentioned experiments, not a live work schedule. A mention does not confirm that an experiment is running now.", newsTitle: "Station dispatches", newsIntro: "Launches, crew changes and everyday life from NASA’s station blog.", read: "Read at NASA ↗", original: "NASA’s original reports in English", allCrew: "Meet the crew & explore science", noResearch: "No research report is currently available.", noCrew: "The crew roster could not be loaded.", noNews: "The news feed is currently unavailable.",
    following: "◎ Follow ISS", freeView: "◎ Free view", orbitPreview: "Next 90 minutes · predicted", orbitUnavailable: "Orbit prediction unavailable", orbitEpoch: "Orbital elements dated", solarNote: "Day/night from solar position · Night lights: NASA 2012 · Illustrative clouds", dataTitle: "How updates work", dataBody: "NASA RSS provides station and research reports. NASA’s expedition page provides the roster and roles; People in Space adds profiles and arrival dates. Refreshes every 10 minutes while visible, with caching and independent source status. Saved data remains available for up to 24 hours during outages. Research reports retain their publication date.", orbitData: "The 90-minute preview uses SGP4 and ISS orbital elements (TLE). Elements older than seven days are rejected. Measured position is separate; altitude on the globe is exaggerated for clarity. Solar position and Earth shadow use an astronomical approximation. Night lights are historical imagery, not live images.", brief: "The orbiting lab, right now.", briefIntro: "Meet the crew, explore recent research and catch up on news from 400 kilometres above Earth.", measured: "ISS illumination", trail: "Measured trail", timeUnknown: "Date unavailable"
  },
  da: {
    nav: "Ombord", kicker: "MENNESKER / VIDENSKAB / KREDSLØB", title: "I dag på ISS.", intro: "Menneskene bag lyspunktet. Forskningen bag missionen.",
    open: "Oplev livet ombord", crewTitle: "Hvem er ombord?", crewIntro: "Stationens besætning ifølge NASA, suppleret med profiler og missionsdata.", expedition: "Ekspedition", people: "mennesker ombord", onboard: "Ombord ifølge NASA", reported: "ISS-besætning ifølge community", commander: "Stationskommandør", engineer: "Flyingeniør", crew: "Besætningsmedlem", arrived: "Ankomst", launched: "Opsendelse", days: "dage siden ankomst", profile: "Åbn profil", source: "Kilde", credit: "Billedkilde / licens", fetched: "Hentet", fresh: "Kilden er tilgængelig", stale: "Senest gemte data", unavailable: "Kilden er ikke tilgængelig", loading: "Henter stationsdata …", retry: "Hent igen", community: "NASA-kontrollen er ikke tilgængelig. Community-listen vises uden angivne roller.", crewNote: "Besætningsskift vises, når kilderne opdateres. En vellykket hentning er ikke en bekræftelse i realtid. Ankomst og opholdslængde kommer fra den supplerende missionskilde.",
    researchTitle: "Forskning i fokus.", researchIntro: "Seneste rapporter fra kredsløbet, enkelt forklaret og med originalkilde.", reportedAt: "Senest omtalt", why: "Hvorfor i rummet?", benefit: "Hvad kan det bruges til?", researchNote: "Kortene viser nyligt omtalte forsøg, ikke en arbejdsplan i realtid. En omtale bekræfter ikke, at forsøget kører lige nu.", newsTitle: "Nyt fra stationen", newsIntro: "Opsendelser, besætningsskift og hverdagen fra NASAs stationsblog.", read: "Læs hos NASA ↗", original: "NASAs originale rapporter på engelsk", allCrew: "Hele besætningen og forskningen", noResearch: "Ingen forskningsrapport er tilgængelig lige nu.", noCrew: "Besætningslisten kunne ikke hentes.", noNews: "Nyhedsfeedet er ikke tilgængeligt lige nu.",
    following: "◎ Følg ISS", freeView: "◎ Fri visning", orbitPreview: "Næste 90 minutter · beregnet", orbitUnavailable: "Baneprognose ikke tilgængelig", orbitEpoch: "Banedata fra", solarNote: "Dag/nat fra solens position · Natlys: NASA 2012 · Illustrative skyer", dataTitle: "Sådan opdateres indholdet", dataBody: "NASA RSS leverer stations- og forskningsnyheder. NASAs ekspeditionsside leverer besætning og roller; People in Space supplerer med profiler og ankomstdata. Opdatering hvert 10. minut på synlige sider med cache og særskilt kildestatus. Gemte data vises i højst 24 timer under udfald. Forskningsnyheder bevarer deres udgivelsesdato.", orbitData: "90-minuttersprognosen bruger SGP4 og ISS-baneelementer (TLE). Elementer ældre end syv dage afvises. Den målte position vises separat; højden på globussen er overdrevet for tydelighed. Solposition og jordskygge bruger en astronomisk tilnærmelse. Natlys er historiske billeder, ikke livebilleder.", brief: "Laboratoriet i kredsløb, nu.", briefIntro: "Mød besætningen, oplev aktuel forskning og læs nyheder fra 400 kilometers højde.", measured: "ISS-belysning", trail: "Målt spor", timeUnknown: "Dato ikke tilgængelig"
  }
};
